### PR TITLE
Added automatic and unattended installation of QtCreator

### PR DESCRIPTION
**Pull request by rkrauseics**
Step 1 - as in email :-)

### CODE REVIEW

**Comment by gunnarx** [comment]
As you know we're using another method to get Qt and QtCreator into the image for now but could consider improving it.

Just to clarify, this install QtCreator but not the Qt libraries right? 

If Qt is solveable as well with a download-and-install without any interaction I'd go for that.
(Of course there is $ apt-get install qt5base and qtcreator, but that tends to be out of date quite quickly I feel? 
There is always the option of building it from source but it's huge.   I'm not feeling the need to have continuous integration on every single modification of the Qt libraries, so that would have to be a more infrequent build event!

**Comment by rkrauseics** [comment]
The same process used here for the QtCreator installation can be used for
the installation of Qt itself.
I think I can work that out and test that after the AMM .

Roland

**Comment by gunnarx** [comment]
Hi @rkrauseics 

If it's possible to provide a similar script that will download and install a chosen Qt binary distribution (libraries) without any user interaction then I might consider switching to that.  Do you have something like it somewhere?

Regarding the settings, please consider enabling the installation of source code also - at least it's sometimes important that I have have access to the right corresponding source to provide it for license compliance.

**Comment by gunnarx** [comment]
No progress and I think a major rehaul on SDE might use other methods anyway.  Since this yet another approach was created [here](https://github.com/Pelagicore/pelux-sde)

**Pull request closed without merging**
